version: '3'
services:
  nginx:
    build: ./docker/nginx
    container_name: cpz-dev
    image: cpz-dev
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    ports:
      - 80:80
      - 8080:8888
