version: '3.3'
services:
  redis-master:
    image: redis:5.0.12
    hostname: redis-master
    volumes:
      - redis_master:/data
    ports:
      - '6379:6379'

  redis-slave:
    image: redis:5.0.12
    hostname: redis-slave
    volumes:
      - redis_slave:/data
    ports:
      - '6479:6479'
    command: redis-server --slaveof redis-master 6379

volumes:
  redis_master:
  redis_slave:
